version: "3.0"

services:
  nginx:
    image: ttdev.fidelize.com.br:5000/nginx
    container_name: ng-front
    restart: always
    volumes:
     - ./config:/etc/nginx/conf.d
     - ./:/app/
    networks:
      fidelize_micro_servicos:
        ipv4_address: 10.11.0.210
networks:
  fidelize_micro_servicos:
   external: true


